name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
     
    # sets up .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.102
        
    #get workloads
    - name: Get Workloads
      run: dotnet workload restore src/versteegen.net.client/versteegen.net.client.csproj
      
    - name: Get Wwasmt
      run: dotnet workload install wasm-tools
    
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish src/versteegen.net.client/versteegen.net.client.csproj -c Release -o release --nologo
      
    # changes the base-tag in index.html from '/' to 'versteegen.net' to match GitHub Pages repository subdirectory
    # - name: Change base-tag in index.html from / to versteegen.net
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/versteegen.net\/" \/>/g' release/wwwroot/index.html
      
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: release/wwwroot
      

      
      
